/*
 * If not stated otherwise in this file or this component's Licenses.txt file the
 * following copyright and licenses apply:
 *
 * Copyright 2015 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

/**********************************************************************
   Copyright [2014] [Cisco Systems, Inc.]
 
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
 
       http://www.apache.org/licenses/LICENSE-2.0
 
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
**********************************************************************/

/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "netSnmpTutorialMIB.h"

static int g_nstAgentModuleObject = 100;
static int g_nstAgentModuleObject_bak;
static int g_nstAgentSubagentObject = 200;
static int g_nstAgentSubagentObject_bak;
static int g_nstAgentPluginObject = 200;
static int g_nstAgentPluginObject_bak;

/** Initializes the netSnmpTutorialMIB module */
void
init_netSnmpTutorialMIB(void)
{
    const oid       nstAgentModuleObject_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 2, 4, 1, 1, 1 };
    const oid       nstAgentSubagentObject_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 2, 4, 1, 1, 2 };
    const oid       nstAgentPluginObject_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 2, 4, 1, 1, 3 };

    DEBUGMSGTL(("netSnmpTutorialMIB", "Initializing\n"));

    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("nstAgentModuleObject",
                             handle_nstAgentModuleObject,
                             nstAgentModuleObject_oid,
                             OID_LENGTH(nstAgentModuleObject_oid),
                             HANDLER_CAN_RWRITE));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("nstAgentSubagentObject",
                             handle_nstAgentSubagentObject,
                             nstAgentSubagentObject_oid,
                             OID_LENGTH(nstAgentSubagentObject_oid),
                             HANDLER_CAN_RWRITE));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("nstAgentPluginObject",
                             handle_nstAgentPluginObject,
                             nstAgentPluginObject_oid,
                             OID_LENGTH(nstAgentPluginObject_oid),
                             HANDLER_CAN_RWRITE));
}

int
handle_nstAgentModuleObject(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *reqinfo,
                            netsnmp_request_info *requests)
{
    int             ret;
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 &g_nstAgentModuleObject,
                                 sizeof(g_nstAgentModuleObject));
        break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
    case MODE_SET_RESERVE1:
        /*
         * or you could use netsnmp_check_vb_type_and_size instead 
         */
        ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
        if (ret != SNMP_ERR_NOERROR) {
            netsnmp_set_request_error(reqinfo, requests, ret);
        }
        break;

    case MODE_SET_RESERVE2:
        g_nstAgentModuleObject_bak = g_nstAgentModuleObject;
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        g_nstAgentModuleObject = *(requests->requestvb->val.integer);
        break;

    case MODE_SET_COMMIT:
        break;

    case MODE_SET_UNDO:
        g_nstAgentModuleObject = g_nstAgentModuleObject_bak;
        break;

    default:
        /*
         * we should never get here, so this is a really bad error 
         */
        snmp_log(LOG_ERR,
                 "unknown mode (%d) in handle_nstAgentModuleObject\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_nstAgentSubagentObject(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *reqinfo,
                            netsnmp_request_info *requests)
{
    int             ret;
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 &g_nstAgentSubagentObject,
                                 sizeof(g_nstAgentSubagentObject));
        break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
    case MODE_SET_RESERVE1:
        /*
         * or you could use netsnmp_check_vb_type_and_size instead 
         */
        ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
        if (ret != SNMP_ERR_NOERROR) {
            netsnmp_set_request_error(reqinfo, requests, ret);
        }
        break;

    case MODE_SET_RESERVE2:
        g_nstAgentSubagentObject_bak = g_nstAgentSubagentObject;
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        g_nstAgentSubagentObject = *(requests->requestvb->val.integer);
        break;

    case MODE_SET_COMMIT:
        break;

    case MODE_SET_UNDO:
        g_nstAgentSubagentObject = g_nstAgentSubagentObject_bak;
        break;

    default:
        /*
         * we should never get here, so this is a really bad error 
         */
        snmp_log(LOG_ERR,
                 "unknown mode (%d) in handle_nstAgentSubagentObject\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_nstAgentPluginObject(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *reqinfo,
                            netsnmp_request_info *requests)
{
    int             ret;
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 &g_nstAgentPluginObject,
                                 sizeof(g_nstAgentPluginObject));
        break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
    case MODE_SET_RESERVE1:
        /*
         * or you could use netsnmp_check_vb_type_and_size instead 
         */
        ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
        if (ret != SNMP_ERR_NOERROR) {
            netsnmp_set_request_error(reqinfo, requests, ret);
        }
        break;

    case MODE_SET_RESERVE2:
        g_nstAgentPluginObject_bak = g_nstAgentPluginObject;
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        g_nstAgentPluginObject = *(requests->requestvb->val.integer);
        break;

    case MODE_SET_COMMIT:
        break;

    case MODE_SET_UNDO:
        g_nstAgentPluginObject = g_nstAgentPluginObject_bak;
        break;

    default:
        /*
         * we should never get here, so this is a really bad error 
         */
        snmp_log(LOG_ERR,
                 "unknown mode (%d) in handle_nstAgentPluginObject\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
